# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements/devl.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test

before_script:
  - createuser -U postgres -s travis
  - psql -c 'CREATE DATABASE pgextras_unittest' -U postgres

# install different versions of postgres, taken from
# https://github.com/clkao/plv8x/blob/master/.travis.yml
before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common postgresql-contrib
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo echo "shared_preload_libraries = 'pg_stat_statements'" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart

env:
  - PGVERSION=9.2
  - PGVERSION=9.1
